### ISSUE TITLE
RFE: Add labels and annotation support to kind: namespace

### ISSUE THREAD

**Issue by claudiol** [validatedpatterns/common#282]
This is coming from the TelCo team who I am working on creating the npss-tnc community pattern.

We currently support the creation of namespaces.  There are instances in which users need to add additional **annotations** and **labels** to a **namespace** manifest.  For example:

```
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
```

The implementation would require us to update the way we define namespaces in our values file. The proposal would be something like this:

```
namespaces:
- name: namespaceName
  labels:
  - name: labelName
    value: labelValue
  annotations:
  - name: "annotationName"
    value: "annotationValue"
```

Question for the team is:
* Do we want to support this in future versions of **common** ?
* Or do we just have users create a **Namespace** manifest with the appropriate **annotations** and **labels** to be applied by openshift-gitops?
