### ISSUE TITLE
override/empty  target namespace 

### ISSUE THREAD

**Issue by Ladanow** [validatedpatterns/common#296]
Some operators are not compatible with adding targetNamespace as their own, this is automatically done when we create a new namespace.

for example, `performance-addon-operator` can't monitor its own namespace.

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1","kind":"OperatorGroup","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"npss-tnc-hub"},"name":"openshift-performance-addon-operator-operator-group","namespace":"openshift-performance-addon-operator"},"spec":{"targetNamespaces":["openshift-performance-addon-operator"]}}
```
