### ISSUE TITLE
Add extraParameters to values.schema.json

### ISSUE THREAD

**Issue by claudiol** [validatedpatterns/common#510]
### Problem Statement
   The current **clustergroup** schema does not allow the definition of **extraParameters** under the **main** section of a values file.

### Caveat
The user defined variables in the **extraParameters** section would only be applied if the user deploys the pattern via the command, using `./pattern.sh make install` or `./pattern.sh make operator-deploy` and not via the OpenShift Validated Patterns Operator UI. 

### Proposed Fix Description
  Add the **extraParameters** to the definition of **Main.properties** in the values.schema.json:

```yaml    
...
  "Main": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "clusterGroupName"
      ],
      "title": "Main",
      "description": "This section contains the 'main' variables which are used by the install chart only and are passed to helm via the Makefile",
      "properties": {
        "clusterGroupName": {
          "type": "string"
        },
        "extraParameters": {
          "type": "array",
          "description": "Pass in extra Helm parameters to all ArgoCD Applications and the framework."
        },
...
```
This will allow users to define extra parameters that will be added by the framework to the ArgoCD applications it creates.

### More Detailed Description

* We currently have the following code in **common/operator-install/templates/pattern.yaml**:
```yaml
  extraParameters:
{{- range .Values.main.extraParameters }}
  - name: {{ .name | quote }}
    value: {{ .value | quote }}
{{- end }} {{/* range .Values.main.extraParameters */}}
{{- end }} {{/* if .Values.main.extraParameters */}}
```
* This fix allows a user to define the **extraParameters** in a values file under the **main** section.
* A user would do the following to define their **extraParameters** variables:
```yaml
main:
  clusterGroupName: datacenter
  multiSourceConfig:
    enabled: false
  experimentalCapabilities: initcontainers
  extraParameters:
    - name: clusterEnvironment
      value: prod
```
* If you define extraParameters under the **main** section of the values files in a pattern these parameters are added by the Validated Patterns operator to Pattern CR.  You can get the list of pattern CRs by using the `oc get pattern -n openshift-operators` command.
```yaml
apiVersion: v1
items:
- apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
  kind: Pattern
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gitops.hybrid-cloud-patterns.io/v1alpha1","kind":"Pattern","metadata":{"annotations":{},"name":"industrial-edge","namespace":"openshift-operators"},"spec":{"clusterGroupName":"datacenter","experimentalCapabilities":"initcontainers","extraParameters":[{"name":"environment","value":"dev"}],"gitSpec":{"targetRepo":"https://github.com/claudiol/industrial-edge.git","targetRevision":"deploy-industrial"},"multiSourceConfig":{"enabled":false}}}
    creationTimestamp: "2024-05-15T16:23:18Z"
    finalizers:
    - foregroundDeletePattern
    generation: 2
    name: industrial-edge
    namespace: openshift-operators
    resourceVersion: "565790"
    uid: 233d6200-7de2-4221-94e3-9c36351db8cc
  spec:
    clusterGroupName: datacenter
    experimentalCapabilities: initcontainers
    extraParameters:
    - name: clusterEnvironment
      value: dev
   ...
```
* In turn the operator adds these **extraParameters** to the **extraParametersNested** section as key/value pairs in the Cluster Wide ArgoCD Application created by the Validated Patterns operator.  
* This allows the user to define extra parameters that would be useful to **user provided** Helm charts for their particular pattern.
* The clustergroup Helm chart will add these parameters to each ArgoCD Application created by the framework
* The Application template found in common/clustergroup/templates/plumbing/applications.yaml will add the defined parameters as key/value pairs under the **Parameters** of each ArgoCD Application created by the framework.
* Below is the Helm template code that includes these parameters:
```yaml
          {{- range $k, $v := $.Values.extraParametersNested }}
          - name: {{ $k }}
            value: {{ printf "%s" $v | quote }}
          {{- end }}
```
